# -*- coding: utf-8 -*-
"""Copy of Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18o6SOe5boQ5rM1AEKEjpqq1DnYHJVTKJ
"""

pip install supabase

from supabase import create_client

# SUPABASE_URL = "https://your-project.supabase.co"
# SUPABASE_KEY = "your-anon-key"

# supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

"""# Toy Example


Useful variables (both pandas dataframe) per week:


*   `recommendations`: top k recommendated zipcode, updated each week
*   `all_weeks_df`: culmulative screening reports include screening weeks, outcomes.
*   `week_df`: only counts for current week

## Utilities:

this section should not be modoified, useful variables is in the next section
"""

import numpy as np
import pandas as pd

# === Utility ===
def logsumexp_trick(x):
    x_max = np.max(x)
    exp_x = np.exp(x - x_max)
    return exp_x / exp_x.sum()

# === SimPeru ===
class SimStub:
    def __init__(self, n_sites):
        self.n_sites = n_sites
        self.status = np.zeros(n_sites, dtype=bool)
        self.current_states = np.zeros((n_sites, 2))  # Dummy

    def step(self, actions):
        self.status = actions.astype(bool)

    # def get_observable(self):
    #     # Dummy: [diagnosed, screened-diagnosed]
    #     return np.random.randint(0, 5, size=(self.n_sites, 2))

    def get_observable(self):
        # Dummy: [diagnosed, screened-diagnosed]
        self.current_states = np.zeros((self.n_sites, 2))
        for i in range(self.n_sites):
            if self.status[i] == 1:
                screened = np.random.randint(5, 15)
                diagnosed = np.random.binomial(screened, 0.2)
                self.current_states[i, 0] = diagnosed
                self.current_states[i, 1] = screened - diagnosed
        return self.current_states

    def reset(self):
        pass

class EnvStub:
    def update(self, sim):
        pass

# === EXP3 Interactive ===
# Production path: use backend.bandit.exp3.Exp3Interactive (real ticket outcomes).
# This Colab class remains for offline/toy simulation only.
# decision making
class exp3_interactive:
    def __init__(self, sim, env, T, K=1):
        self.sim = sim
        self.env = env
        self.K = K
        self.n_arms = sim.n_sites
        self.p = np.ones(self.n_arms) / self.n_arms

        self.cum_reward = np.zeros(self.n_arms)
        self.his_reward = np.zeros((self.n_arms, T))

        self.L = 100
        self.eta = np.sqrt(np.log(self.n_arms) / (T * self.n_arms * self.L**2))

        # self.curr_total_screened = 0
        # self.curr_total_diagnosed = 0

    def apply_user_selection(self, selected_indices):
        self.env.update(self.sim)

        actions = np.zeros(self.n_arms, dtype=int)
        actions[selected_indices] = 1

        self.sim.step(actions=actions)
        observation = self.sim.get_observable()

        # self.curr_total_screened = observation.sum()
        # self.curr_total_diagnosed = observation[:, 0].sum()

        indx = observation[:, 0] == 0
        self.reward = np.zeros(len(observation.sum(axis=1)))
        self.reward[indx] = - observation.sum(axis=1)[indx] / (0.1 + observation[:, 0][indx])
        self.reward[~indx] = - observation.sum(axis=1)[~indx] / observation[:, 0][~indx]

        R_hat = np.zeros(self.n_arms)
        R_hat[selected_indices] = self.reward[selected_indices]  / self.p[selected_indices]

        self.cum_reward += R_hat
        self.p = logsumexp_trick(self.eta * self.cum_reward)
        self.p = (1 - self.eta) * self.p + self.eta / self.n_arms


    def get_site_recommendation(self, top_k=None):
        """
        Returns a DataFrame with current model recommendations (not cumulative).
        Fields:
        - zip_code
        - priority (model score)
        - rank
        If top_k is provided, limits to top_k arms.
        """
        sorted_indices = np.argsort(-self.p)
        probs_sorted = self.p[sorted_indices]

        if top_k:
            sorted_indices = sorted_indices[:top_k]
            probs_sorted = probs_sorted[:top_k]
        else:
            sorted_indices = sorted_indices
            probs_sorted = probs_sorted

        recommendations = {
            "zip_code": [f"{i}" for i in sorted_indices],
            "priority": probs_sorted,
            "rank": np.arange(1, len(sorted_indices) + 1)
        }
        return recommendations

    def get_site_report(self, t, selected_indices):
        """
        Returns report only for selected arms (non-zero screened).
        Each entry includes:
        - zip_code: site_{i}
        - screened_count: diagnosed + others
        - positive_count: diagnosed
        - priority: from self.p
        - notes: empty
        """
        obs = self.sim.get_observable()
        report = []
        for i in selected_indices:
            screened_count = int(obs[i].sum())
            positive_count = int(obs[i, 0])
            report.append({
                "screening_week": t,
                "zip_code": f"{i}",
                "screened_count": screened_count,
                "positive_count": positive_count,
                "notes": ""
            })
        return report



    def reset(self, reset_sim=True):
        if reset_sim:
            self.sim.reset()
        self.p = np.ones(self.n_arms) / self.n_arms
        self.cum_reward = np.zeros(self.n_arms)
        self.his_reward = np.zeros_like(self.his_reward)
        self.curr_total_screened = 0
        self.curr_total_diagnosed = 0

"""## Potentially Useful Section

This section should contains all variables you need.
"""

# === Driver Function ===
def run_interactive_session(T=10, K=2, n_sites=10, top_k = 10):
    sim = SimStub(n_sites)
    env = EnvStub()
    model = exp3_interactive(sim, env, T, K)
    all_weeks_df = pd.DataFrame()

    for t in range(T):
        print(f"\n--- Week {t+1} ---")

        # Show (ID, rank scores)
        recommendations = model.get_site_recommendation(top_k=top_k)
        recommendations = pd.DataFrame(recommendations)
        print("\n Current Site Recommendations:")
        print(recommendations.to_string(index=False))

        recommendations.to_csv("site_recommendations.csv", index=False)

        # Input arm selection
        selected = input(f"Select {K} ids indices (comma-separated): ")
        selected_indices = list(map(int, selected.strip().split(",")))

        model.apply_user_selection(selected_indices)

        # Output per-site report (for display)
        report = model.get_site_report(t+1, selected_indices)

        # accumulated dataframe
        week_df = pd.DataFrame(report)
        all_weeks_df = pd.concat([all_weeks_df, week_df], ignore_index=True)
        # print("\nCurrent Weekly Report:")
        # print(week_df)
        print(all_weeks_df)
        all_weeks_df.to_csv("cumulative_screening_report.csv", index=False)




# === Run It ===
if __name__ == "__main__":
    run_interactive_session(T=10, K=2, n_sites=100, top_k = 10)

"""# Real Example

[In the process of development, please use above for now]

This one should shares exactly the same output format as above.

ToBeDone:

*   link with real zip code

## Prep, Loading:

please just run below cells sequentially and upload the input file
"""

!git clone https://github.com/JiujiaZ/adapt-tb.git

cd /content/adapt-tb

from google.colab import files

# Upload the zip file
uploaded = files.upload()

import os
import zipfile

# Create a specific directory if it doesn't already exist
os.makedirs('/content/adapt-tb/data/input', exist_ok=True)

# Unzip the uploaded folder
with zipfile.ZipFile('input.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/adapt-tb/data/input')

import pandas as pd
import matplotlib.pyplot as plt
import pickle
from src.simulator import *
# from src.policies import *
from src.Environment import *
from src.tools import *
import numpy as np

class LinUCB_interactive:
    def __init__(self, sim, env, T, alpha=1.0, lam=1.0, K=1, reg=None):
        self.sim = sim
        self.env = env
        self.T = T
        self.K = K
        self.alpha = alpha
        self.lam = lam

        self.n_arms = sim.n_sites
        self.n_dims = env.n_dims

        self.A = np.tile(np.eye(self.n_dims) * self.lam, (self.n_arms, 1, 1))
        self.b = np.zeros((self.n_arms, self.n_dims, 1))
        self.theta = np.zeros((self.n_arms, self.n_dims, 1))

        self.theta_star = np.zeros((self.n_arms, self.n_dims, 1)) if reg is None else reg
        self.t = 1
        self.reward = np.zeros(self.n_arms)

        self.last_context = None

    def apply_user_selection(self, selected_indices):
        self.env.update(self.sim)

        actions = np.zeros(self.n_arms, dtype=int)
        actions[selected_indices] = 1

        self.sim.step(actions=actions)
        observation = self.sim.get_observable()

        indx = observation[:, 0] == 0
        self.reward = np.zeros(len(observation.sum(axis=1)))
        self.reward[indx] = - observation.sum(axis=1)[indx] / (0.1 + observation[:, 0][indx])
        self.reward[~indx] = - observation.sum(axis=1)[~indx] / observation[:, 0][~indx]

        # get pulled arm
        indx = np.where(self.sim.status)[0]
        # update: over each selected arm:
        for n, i in enumerate(indx):
            observe_feature = self.last_context[i].reshape(-1, 1)

            # no decay update
            self.A[i] += observe_feature @ observe_feature.T
            self.b[i] += self.reward[n] * observe_feature

        self.t += 1

    def get_site_recommendation(self, top_k=None):
        """
        Returns a dictionary with current model recommendations (not cumulative).
        Fields:
        - zip_code
        - priority (model score)
        - rank
        If top_k is provided, limits to top_k arms.
        """
        self.env.update(self.sim)
        X = self.env.get_context()
        self.last_context = X

        scores = np.zeros(self.n_arms)
        for i in range(self.n_arms):
            A_inv = np.linalg.pinv(self.A[i])
            decay = (self.T - self.t) / self.T
            self.theta[i] = A_inv @ (self.b[i] + self.lam * decay * self.theta_star[i])
            scores[i] = (self.theta[i].T @ X[i] + self.alpha * np.sqrt(X[i].T @ A_inv @ X[i])).item()

        sorted_indices = np.argsort(-scores)
        probs_sorted = scores[sorted_indices]

        if top_k:
            sorted_indices = sorted_indices[:top_k]
            probs_sorted = probs_sorted[:top_k]

        recommendations = {
            "zip_code": [f"{i}" for i in sorted_indices],
            "priority": probs_sorted,
            "rank": np.arange(1, len(sorted_indices) + 1)
        }
        return recommendations

    def get_site_report(self, t):
        """
        Returns report only for selected arms (non-zero screened).
        Each entry includes:
        - screening_week
        - zip_code
        - screened_count: diagnosed + others
        - positive_count: diagnosed
        - notes: ""
        """
        obs = self.sim.get_observable()
        report = []
        indx = np.where(self.sim.status)[0]
        # update: over each selected arm:
        for n, i in enumerate(indx):
            screened_count = int(obs[n].sum())
            positive_count = int(obs[n, 0])
            report.append({
                "screening_week": t,
                "zip_code": f"{i}",
                "screened_count": screened_count,
                "positive_count": positive_count,
                "notes": ""
            })
        return report

    def reset(self, reset_sim=True):
        if reset_sim:
            self.sim.reset()
            self.env.reset()

        self.A = np.tile(np.eye(self.n_dims) * self.lam, (self.n_arms, 1, 1))
        self.b = np.zeros((self.n_arms, self.n_dims, 1))
        self.theta = np.zeros((self.n_arms, self.n_dims, 1))
        self.reward = np.zeros(self.n_arms)
        self.t = 1
        self.last_context = None

"""## Potentially useful section

This section should contains all variables that you will need
"""

def run_real_interactive_session(K=1, r = 2, d = 0.33, T = 100, top_k = 10):

    print(f'Using K={K}, r={r}, and d={d}')

    # Read parameters from saved pickle files
    params_file = f'data/parameters/parameters_r{r}_d{int(d * 100)}.pkl'
    with open(params_file, 'rb') as f:
        parameters = pickle.load(f)

    transitions = parameters['transitions']
    initial_states = parameters['initial_states']
    A = parameters['A_potential']
    pi = parameters['travel_pi']

    # Load features
    location_ids = pd.read_csv('data/input/location_ids.csv').iloc[:, :1].to_numpy()
    features = pd.read_csv('data/input/features.csv').iloc[:, 1:].to_numpy()
    features_name = pd.read_csv('data/input/features.csv').columns[1:]

    # Load site_reg
    params_file = f'data/input/site_reg.pkl'
    with open(params_file, 'rb') as f:
        site_reg = pickle.load(f)


    residents = Residents(transitions=transitions, initial_states=initial_states)
    sim = ScreenSites(N=A, weights=pi, residents=residents)
    environment = Envrionment(features_name, features, location_ids)
    # model = exp3_interactive(sim, environment, T, K=K)
    model = LinUCB_interactive(sim, environment, T, alpha=1, lam=1, K=K, reg=site_reg)
    all_weeks_df = pd.DataFrame()


    for t in range(T):
        print(f"\n--- Week {t+1} ---")

        # Show (ID, rank scores)
        recommendations = model.get_site_recommendation(top_k=top_k)
        recommendations = pd.DataFrame(recommendations)
        print("\n Current Site Recommendations:")
        print(recommendations.to_string(index=False))

        # recommendations.to_csv("site_recommendations.csv", index=False)

        # Input arm selection
        selected = input(f"Select {K} ids indices (comma-separated): ")
        selected_indices = list(map(int, selected.strip().split(",")))

        model.apply_user_selection(selected_indices)

        # Output per-site report (for display)
        report = model.get_site_report(t+1)

        # accumulated dataframe
        week_df = pd.DataFrame(report)
        all_weeks_df = pd.concat([all_weeks_df, week_df], ignore_index=True)
        # print("\nCurrent Weekly Report:")
        # print(week_df)
        print(all_weeks_df)
        # all_weeks_df.to_csv("cumulative_screening_report.csv", index=False)


# === Run It ===
if __name__ == "__main__":
    run_real_interactive_session(K=2, r = 2, d = 0.33, T = 100, top_k = 10)